CC = g++
CFLAGS = -std = c++11
LIBS = -lpthread


OBJECTS = main.o RtmpSession.o RtmpServer.o amf.o BufferReader.o BufferWriter.o \
	  RtmpConnection.o  TcpListener.o TcpSocket.o Threadpool.o

all:main

main: $(OBJECTS)
	$(CC) $(CFLAGS) -o main $(OBJECTS) $(LIBS)

main.o: main.cpp RtmpServer.h
	$(CC) -c main.cpp RtmpServer.h

RtmpServer.o: RtmpServer.cpp RtmpServer.h Threadpool.h TcpListener.h RtmpSession.h
	$(CC) -c RtmpServer.cpp RtmpServer.h Threadpool.h TcpListener.h RtmpSession.h

amf.o: amf.cpp amf.h Common.h BufferReader.h BufferWriter.h
	$(CC) -c amf.cpp BufferReader.h BufferWriter.h

BufferReader.o: BufferReader.cpp BufferReader.h Common.h Socket.h
	$(CC) -c BufferReader.cpp BufferReader.h Common.h Socket.h
 
BufferWriter.o: BufferWriter.cpp BufferWriter.h Common.h Socket.h
	$(CC) -c BufferWriter.cpp BufferWriter.h Common.h Socket.h

RtmpConnection.o: RtmpConnection.cpp RtmpConnection.h amf.h RtmpServer.h\
BufferWriter.h BufferReader.h Socket.h
	$(CC) -c RtmpConnection.cpp cpp RtmpConnection.h amf.h RtmpServer.h\
BufferWriter.h BufferReader.h Socket.h

RtmpSession.o: RtmpSession.cpp 
	$(CC) -c RtmpSession.cpp RtmpSession.h RtmpConnection.h Socket.h

TcpListener.o: TcpListener.cpp TcpListener.h TcpSocket.h
	$(CC) -c TcpListener.cpp TcpListener.h TcpSocket.h

TcpSocket.o: TcpSocket.cpp TcpSocket.h Socket.h Common.h
	$(CC) -c TcpSocket.cpp TcpSocket.h Socket.h Common.h

Threadpool.o: Threadpool.cpp Threadpool.h RtmpConnection.h
	$(CC) -c Threadpool.cpp Threadpool.h RtmpConnection.h

clean :
	rm main *.o
